### ISSUE TITLE
New formal Release

### ISSUE THREAD

**Issue by maphew** [maphew/apt#10]
It's been a **very** long time since I've let anyone know about what's going in apt world, and all of the main commands now do useful work. It's time to update the main Trac instance, and put in a pointer in SVN that points here. 

This is worth doing, even if there isn't anything truly new in what apt does (no new commands or features), mostly better screen reporting, but there are some worthwhile bug fixes too (IMO).

**Comment by amr66** [comment]
Hi maphew, 
thank you for all your fantastic work on apt for OSGeo4W. When I was trying to build a portable Version of QGIS and other packages, I read your post on install from scratch with apt. Unfortunately, apt from the official packages is very old(?) and fails at a lot of points. 
Now i'm using the "fresh" version, directly from repository - and it works! So again: Thank you! I now will try to build my portable GIS-Stick with your apt.py and hopefully will have the possibility to upgrade installed packages!
Don't know if this is the adequate place for asking, but i'll try:
My main problem, from the beginning, is the postinstall part, where i have to change hardcoded or absolute path configurations, to reach "portability". I did this by running the whole installation with my own batch scripts, using apt for downloading packages and dependencies, then unpacking etc. Because all batch files for postinstall come from the providers of each package, its not easy to "patch" these bat files automatically, to make the package portable. And i wasn't able to update the Software. 
Now, when i'm  going to use apt.py, i want a point inside the script to make changes to batch files, before postinstall is started. 
Do you have any idea? Did you ever think about a portable OSGeo4W?

**Comment by jef-n** [comment]
Sounds more like a discussion that should go to the mailing list.  You shouldn't need to change the batch files - everything should refer to %OSGEO4W_ROOT% - unless however the external driver doesn't always the same driver letter.  The postinstall scripts also write the path so some files and those will break.

**Comment by maphew** [comment]
Thank you for the kind words Andreas! They are sincerely appreciated. 

Jurgen is right, this discussion is better on the mailing list, http://lists.osgeo.org/mailman/listinfo/osgeo4w-dev, where we can flesh it out more completely, freely. However: if a particular package is (unnecessarily) not portable it means they're not following the [shell template](http://trac.osgeo.org/osgeo4w/wiki/PackagingInstructions#Applicationbatchfiletemplate). I'd contact the maintainer and encourage them to look at portability (by opening a ticket at http://trac.osgeo.org/osgeo4w/newticket)

I wasn't aware of creatensis and look forward to studying it, thanks Jurgen.

**Comment by jef-n** [comment]
> However: if a particular package is (unnecessarily) not portable it means they're not following the shell template.

Well, that's not always possible - at least not that easy.  I think most of the batch files are "portable", but we  also have configuration file templates that are modified in postinstall using `textreplace`. That's essentially why it exists.

BTW another problem with portability are the `msvcrt` packages - that need to be installed.

**Comment by maphew** [comment]
started a thread: [osgeo4w portability](http://lists.osgeo.org/pipermail/osgeo4w-dev/2015-February/002870.html)

**Comment by amr66** [comment]
Thank you very much,  i'll contribute there! Having a list of non portable postinstall batches!
