### ISSUE TITLE
Use alternate ini option is broken

### ISSUE THREAD

**Issue by maphew** [maphew/apt#41]
```
B:\code\apt>apt --ini b:\o4w-packages\setup_2014-12-01.ini available

GetoptError: option --ini not recognized

B:\code\apt>apt -i b:\o4w-packages\setup_2014-12-01.ini available

IOError: [Errno url error] unknown url type: 'b'

B:\code\apt>apt -i file://b:\o4w-packages\setup_2014-12-01.ini available

IOError: [Errno socket error] [Errno 11004] getaddrinfo failed
```

**Comment by amr66** [comment]
Hm, there is, to me, a strange part of code in the getopt-part, it tries to fetch a url first and than assigns a value from a list object...
`````python
elif o == '--ini' or o == '-i':
          # use either local or url file for setup.ini, was:
          # setup_ini = a
          setup_ini = urllib.urlretrieve(a)
          setup_ini = setup_ini[0]
`````
i guess the bug is from there.

**Comment by amr66** [comment]
I have the same here, too. Strange behaviour, since urllib can open local files with urllib.FancyURLopener. I think, after trying this and that, we hat to catch an error-and better using requests?

**Comment by amr66** [comment]
urlretrieve seems to be quite finicky with url's: Try something like this: r = urllib.urlretrieve("file:///G:/gp2go/info.txt"). Notice that there are three slashes, as the server is missing: file://server/path/to/resource. Anyway, it's a nice idea, to have access to local ans remote ini-files. But we should have a check!

**Comment by amr66** [comment]
`````python
import urllib
import urlparse
import os
urlschemes = ['file', 'ftp', 'gopher', 'hdl', 'http', 'https', 'imap', 'mailto',
'mms', 'news', 'nntp', 'prospero', 'rsync', 'rtsp', 'rtspu', 'sftp', 'shttp',
'sip', 'sips', 'snews', 'svn', 'svn+ssh', 'telnet', 'wais']

def urlretrieve_filename(url):
    # we have a local path
    if os.path.exists(url):
        return url
    # check url
    pr = urlparse.urlparse(url)
    if pr.scheme in urlschemes:
        return urllib.urlretrieve(url)[0]
    else:
        raise ValueError("url %s has no schema, use http:// for example." % url)
`````
May be this could help? For an error like yours I didn't find a way to correct, but now the function distinguishes between local file and url... ParseResult is a class inside urlparse, my variable pr instantiate ParseResult, so we could even check for more, but I see not know to do this:
ParseResult gives: scheme='file', netloc='G:', path='/gp2go/info.txt', params='', query='', fragment=''
for url = "file://g:/gp2go/info.txt", netloc obviously is wrong, because only two slashes are given...
see here: https://docs.python.org/2.7/library/urlparse.html?highlight=urlparse#module-urlparse

**Comment by maphew** [comment]
Thanks for figuring out where the problem came from.  I was looking in a very different direction! *urllib* v1 handled local/remote paths invisibly so I didn't suspect *requests* at all.
